version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor: node/default
    steps:
      # Install node
      - node/install:
          install-yarn: true

      # Checkout repository
      - checkout

      # Download Node dependencies
      - node/install-packages:
          pkg-manager: yarn

      # Run ESlint
      - run:
          name: ESlint
          command: yarn eslint

      - run:
          name: Compile
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ];then
              yarn compile
            fi
      - run:
          name: Deploy to NPM
          command: |
            if [ "${CIRCLE_BRANCH}" = "develop" ];then
              echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
              node ./build/publishDev.js
            fi
